services:
  wordpress:
    container_name: wordpress
    build: ./compose
    restart: always
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.wordpress.rule=Host(\"${WP_DOMAIN}\")"
      - "traefik.http.routers.wordpress.entrypoints=web,websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
    networks:
      web:
      mariadb:
networks:
  web:
    name: web
    external: true
  mariadb:
    name: mariadb
    external: true
